name: EssentialishWarp
version: 0.6.3
main: jp.pgw.kosoado.EssentialishWarp
api-version: "1.21.1"

commands: 
     warp: 
        aliases: [wp]
        description: warp command
        usage: '/warp <warp_name> [<player>]'
     silwarp: 
       aliases: [silwp]
       description: silent warp command
       usage: '/silwarp <warp_name> [<player>]'
     setwarp:
        aliases: [setwp]
        description: set warp
        usage: '/setwarp <warp_name> <sound_name | off> [<group_name>]'
     updwarp: 
       aliases: [updwp]
       description: update warp command
       usage: '/warp <warp_name> <warp | sound> [<sound_name | off>]'
     renwarp: 
       aliases: [renwp]
       description: rename warp command
       usage: '/renwarp <warp_name> <new_warp_name>'
     delwarp:
       aliases: [delwp]
       description: delete warp
       usage: '/delwarp <warp_name>'
     warplist:
       aliases: [wplist]
       description: warp list
       usage: '/warplist [<group_name>]'
     warpgroup:
       aliases: [wpgp]
       description: warp group operation
       usage: '/warpgroup <operation> <name> [<value>]'
        
permissions:
     EssentialishWarp: 
        default: false